// Bundles the Gemini CLI core into a single ES module that can be executed
// by QuickJS inside the Android app.
//
// If `@google/gemini-cli` (or a local source) is available, we bundle the real
// core. Otherwise we write a self-contained stub so the Android build always
// has an asset to ship — the Kotlin bridge also carries an in-memory copy of
// the same stub as a second safety net.

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, 'core-bridge', 'src', 'main', 'assets');
const OUT_FILE = path.join(OUT_DIR, 'gemini-core-bundle.mjs');

fs.mkdirSync(OUT_DIR, { recursive: true });

const STUB_BUNDLE = `// Fallback Gemini Core bundle — generated by esbuild.android.js.
globalThis.GeminiBridge = (function () {
  var state = { config: null, history: [] };
  function now() { return Date.now(); }
  function uid() { return String(now()) + '-' + Math.floor(Math.random() * 1000); }
  function init(configJson) {
    try { state.config = JSON.parse(configJson || '{}'); } catch (_) { state.config = {}; }
    return 'ok';
  }
  function sendMessage(text) {
    var userMsg = { id: uid(), text: String(text), isUser: true, timestamp: now() };
    state.history.push(userMsg);
    var cfg = state.config || {};
    var hasKey = !!(cfg.api_key || cfg.apiKey);
    var reply = hasKey
      ? '[offline stub] The real Gemini core bundle is not packaged. Your message was received: ' + text
      : '[offline stub] No API key configured. Please provide one. Echo: ' + text;
    var aiMsg = { id: uid(), text: reply, isUser: false, timestamp: now() };
    state.history.push(aiMsg);
    return reply;
  }
  function resetSession() { state.history = []; return 'reset'; }
  function loadHistory() { return state.history.slice(); }
  function setConfig(configJson) {
    try { state.config = JSON.parse(configJson || '{}'); } catch (_) { state.config = {}; }
    return 'ok';
  }
  return { init: init, sendMessage: sendMessage, resetSession: resetSession, loadHistory: loadHistory, setConfig: setConfig };
})();
`;

function writeStub(reason) {
  fs.writeFileSync(OUT_FILE, STUB_BUNDLE, 'utf8');
  console.log('[bundler] Wrote stub bundle to', OUT_FILE, reason ? `(${reason})` : '');
}

async function tryBuildReal() {
  let esbuild;
  try {
    esbuild = require('esbuild');
  } catch (_) {
    return { built: false, reason: 'esbuild not installed' };
  }

  const candidates = [
    path.join(__dirname, 'gemini-cli', 'packages', 'core', 'src', 'android-entry.ts'),
    path.join(__dirname, 'node_modules', '@google', 'gemini-cli', 'dist', 'index.js'),
  ];
  const entry = candidates.find((p) => fs.existsSync(p));
  if (!entry) {
    return { built: false, reason: 'no Gemini CLI entry found' };
  }

  console.log('[bundler] Building real Gemini core bundle from:', entry);
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: ['es2020'],
    outfile: OUT_FILE,
    minify: true,
    external: ['fs', 'path', 'os', 'child_process', 'http', 'https', 'stream'],
    banner: { js: '// Auto-generated by esbuild.android.js. Do not edit.' },
    logLevel: 'info',
  });
  return { built: true };
}

(async () => {
  try {
    const result = await tryBuildReal();
    if (result.built) {
      console.log('[bundler] Real bundle ready at', OUT_FILE);
    } else {
      writeStub(result.reason);
    }
  } catch (e) {
    console.error('[bundler] Real build failed, falling back to stub:', e.message);
    writeStub('real build threw');
  }
})();
